# Generated by Django 5.0.2 on 2024-07-14 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subadmin_user',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user_password', models.CharField(blank=True, max_length=128, null=True)),
                ('user_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
