# Generated by Django 5.0.2 on 2024-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
