# Generated by Django 5.0.2 on 2024-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_service_img2_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
